Challenge deploy
sdslabs/katana pull request #61
Opened 2023-06-07 12:57 UTC by ashpect

/deploy and /delete:challenge routes for challenge. Creates challenge folder, then challenge folder, copies zip, unzips , creates image, deploys the image along with its Nodeport service. Delete route deletes the deployment and service of the challenge across all namespaces.

2023-06-17 19:23 UTC, ashpect commented on services/master/controllers/deploy.go
> +	fmt.Println(dirPath + "/chall/" + foldername + "/" + foldername)
will do

2023-06-17 19:23 UTC, ashpect commented on services/master/controllers/deploy.go
> +		if token := form.Value["token"]; len(token) > 0 {
It was something for testing, removed

2023-06-27 11:20 UTC, Bisht13 requested changes

2023-06-27 11:20 UTC, Bisht13 commented on lib/utils/deploy.go
> +	g "github.com/sdslabs/katana/configs"
"github.com/sdslabs/katana/configs" imported but not used as g (typecheck)

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/createService.go
> +	g "github.com/sdslabs/katana/configs"
"github.com/sdslabs/katana/configs" imported but not used as g (typecheck)

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/createService.go
> +func CreateService(chall_name, team_name string) (string, error) {
Argument variable naming convention

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/createService.go
> +	team_namespace := team_name + "-ns"
Naming convention

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/createService.go
> +			return "", nil
Return the URL

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/deleteChall.go
> +	g "github.com/sdslabs/katana/configs"
"github.com/sdslabs/katana/configs" imported but not used as g (typecheck)

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/deleteChall.go
> +func DeleteChallenge(chall_name string) error {
Argument variable naming convention

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/deleteChall.go
> +	totalteams := utils.GetTeamNumber()
Naming Convention

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/deleteChall.go
> +		deps, err := deploymentsClient.Get(context.TODO(), chall_name, metav1.GetOptions{})
Better naming

2023-06-27 11:20 UTC, Bisht13 commented on services/challengedeployerservice/deleteChall.go
> +		flag := 0
The entire implementation can be done without creating a flag

2023-06-27 11:20 UTC, Bisht13 commented on services/master/controllers/deploy.go
> +func challcopy(dirPath, challengename, challengetype string) {
Naming convention

2023-06-27 11:20 UTC, Bisht13 commented on services/master/controllers/deploy.go
> +func buildimage(folderName string) {
Naming convention

2023-06-27 11:20 UTC, Bisht13 commented on services/master/controllers/deploy.go
> +func createfolder(challengename string) (message int, newDirPath string) {
Naming convention

2023-07-12 20:25 UTC, Bisht13 commented on services/master/controllers/challengeUpdate.go
>  	cmd := exec.Command("docker", "build", "-t", dir, "./teams/"+dir)
Use BuildDockerImage() from utils

2023-08-10 15:42 UTC, merged